server.servlet.context-path: /qantas

security.oauth2.resource.filter-order: 3

spring:
  h2:
    console.enabled: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



logging.level:
  org.springframework.security.oauth2: debug

